// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodingWithCalvin.CouchbaseStudio
{
    internal sealed partial class Vsix
    {
        public const string Id = "VS-CouchbaseStudio";
        public const string Name = "Couchbase Studio";
        public const string Description = @"Couchbase Studio is an extension to Visual Studio that will assist in communication to a Couchbase Server /Capella during the development process.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Coding With Calvin";
        public const string Tags = "couchbase, capella";
    }
}
